In [17]:
"""
1. Você tem uma lista de número: [6,7,4,7,8,4,2,5,7,&#39;hum&#39;, &#39;dois&#39;]. A ideia do exercício é
tirar a média de todos os valores contidos na lista, porém para fazer o cálculo
precisa remover as strings.
"""

#function recieve list, calculate mean for int values
def calcList(list1):
  varSum = 0
  varQtyInt = 0
  for num in list1:
    if type(num) is not str:
      varSum = varSum + num
      varQtyInt = varQtyInt + 1

  result = varSum/varQtyInt
  return result 

#set variables
listNums = [6,7,4,7,8,4,2,5,7,'hum', 'dois']

#call function
calcList(listNums)

5.555555555555555

In [13]:
"""
2. crie um método que receba duas matrizes, some os valores total de cada matriz e
depois multiple o resultado delas e retorne o valor.
"""

#function to sum list values
def sumList(list1):
  if type(list1) is not list:    
    return ("Lista informada não contém o formato 'list'")
  else:
    varSum = 0
    for num in list1:
      if type(num) is not str:
        varSum = varSum + num  
  return varSum

#function to cal sumList functions and multiply values
def calcLists(list1,list2):
  if type(list1) is not list or type(list2) is not list:    
    return ("Listas informadas não contém o formato 'list'")
  else:    
    result = sumList(list1) * sumList(list2)
    return result

#set variables
firstList = [2,2,2]  
secondList = [2,2,2]

#call function
calcLists(firstList,secondList)

36

In [49]:
"""
3. Criar uma matriz nxm (n = 5, m =7)
a. faça a matriz transposta desta matriz
b. somar toda matrix
c. somar todas as colunas
d. somar todas as linhas.
e. retorne o maior valor
f. retorne o menor valor.
"""

#import libs
import numpy as np

#create array nxm (n = 5, m =7)
varArray = np.array(np.arange(35))
varArray.shape = (5,7)

#a 
print("A)\n",np.transpose(varArray))

#b
print("B)\n",varArray.sum())

#c
print("C)\n",varArray.sum(axis=0))

#d
print("D)\n",varArray.sum(axis=1))

#e
print("E)\n",varArray.argmin())

#f
print("F)\n",varArray.argmax())

A)
 [[ 0  7 14 21 28]
 [ 1  8 15 22 29]
 [ 2  9 16 23 30]
 [ 3 10 17 24 31]
 [ 4 11 18 25 32]
 [ 5 12 19 26 33]
 [ 6 13 20 27 34]]
B)
 595
C)
 [ 70  75  80  85  90  95 100]
D)
 [ 21  70 119 168 217]
E)
 0
F)
 34


In [65]:
"""
4. Crie uma matriz nxn (n=5). Agora some essa matriz com a matriz do exercício 3.
"""

#import libs
import numpy as np

#func to sum two array values
def sumNpArray(array0,array1):
  if not isinstance(array0, np.ndarray) or not isinstance(array1, np.ndarray):   
    return ("Lista informada não contém o formato 'Numpy Array'")
  else:
    varSum = array0.sum() + array1.sum()
    return varSum
    
#create array nxm (n = 5, m =7)
varArray0 = np.array(np.arange(35))
varArray0.shape = (5,7)

#create array nxm (n = 5, m =5)
varArray1 = np.array(np.arange(25))
varArray1.shape = (5,5)

sumNpArray(varArray0 ,varArray1)

895

In [67]:
"""
5. crie um array de números que vai de 0 a 1000.
"""

#import libs
import numpy as np

np.arange(1001)



array([   0,    1,    2, ...,  998,  999, 1000])

In [68]:
"""
6. crie uma matriz só de zeros.
"""
#import libs
import numpy as np

np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])